version: '3.3'


services:
  app:
    image: nvcr.io/nvidia/pytorch:23.10-py3
    volumes:
      - ../..:/workspace:cached
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    shm_size: '2G'
    stdin_open: true
    tty: true